---
title: "R Notebook"
output: html_notebook
params:
  serie: '3em'
---


```{r}
library(tidyverse)
library(caret)
```

# Modelo v1: 0,701
```{r modelo v1}
url <- paste0("output/v1/ranking", params$serie, ".csv")
df <- read.csv2(url, na = "") 
df <- df %>% 
  select(id_escola:media)
head(df)
```
## Nivel_socioeconomico
```{r var1}
df <- df %>% 
  mutate(nivel_socio_economico = as.character(nivel_socio_economico),
        nivel_socio_economico = 
               factor(case_when(
                 nivel_socio_economico %in% c('Nível III') ~ 'Nível IV',
                 nivel_socio_economico %in% c('Nível VII') ~ 'Nível VI',
                         TRUE ~ nivel_socio_economico)))
```
# Input Missing
```{r}
df <- df %>% mutate(
  nascidos_vivos_mae18_2019_imp = replace_na(nascidos_vivos_mae18_2019_imp, mean(nascidos_vivos_mae18_2019_imp, na.rm = T))
)
summary(df$nascidos_vivos_mae18_2019_imp)
```
# CV
```{r createfolds}
set.seed(231192)
myFolds <- createFolds(df$media, k = 5)
trControl <- trainControl(
  method = "cv",
  number = 5,
  index = myFolds
)

results <- data.frame(fold = c('Fold 1', 'Fold 2', 'Fold 3', 'Fold 4', 'Fold 5'))
results
```
# INSE Saresp: 0,706 e 0.702(input by group)
```{r import inse}
inse <- read_csv2("data/saresp/INSE_Geral 2018_1_0.csv")
colnames(inse) <- c("codesc","nome","dir","mun","inse")
inse <- inse %>% 
  transmute(id_escola = as.integer(paste0("35",str_pad(codesc,6,pad = "0"))),
            inse)
head(inse)
```

```{r cruza inse}
teste <- df %>% 
  left_join(inse, by = "id_escola")
summary(teste$inse)
teste %>% group_by(nivel_socio_economico) %>% summarise(inse = mean(inse, na.rm = T))
```

```{r input inse}
teste <- teste %>% 
  #mutate(inse = replace_na(inse, mean(inse, na.rm = T)))
  group_by(nivel_socio_economico) %>%
    mutate(
        inse = replace_na(inse, mean(inse, na.rm = T))
    ) %>% 
  ungroup()
summary(teste$inse)
teste %>% group_by(nivel_socio_economico) %>% summarise(inse = mean(inse, na.rm = T))
```
```{r lm inse}
set.seed(231192)
model_ranger <- train(media ~ nivel_socio_economico + tx_resp_q017e_A + tx_resp_q005_F * tx_resp_q004_F * tx_resp_q004_E + tx_resp_q002_A + tx_resp_q010d_B + tx_resp_q009c_A + tx_resp_q012_A + tx_resp_q010i_B +              nascidos_vivos_mae18_2019_imp + inse,
                        data = teste %>% select(-id_escola),
                        method = "lm",
                        metric = "Rsquared",
                        trControl = trControl)


results$rf <- model_ranger$resample$Rsquared
results
mean(results$rf)
```

# Saresp: 0.6999666
```{r import saresp prop}
saresp <- read_csv2(paste0("output/selecao/saresp_v1_", params$serie,".csv"))
head(saresp)
```
```{r cruza saresp}
teste <- df %>% 
  left_join(saresp, by = "id_escola")
summary(teste)
```


```{r lm q23_D_spp}
set.seed(231192)
model_ranger <- train(media ~ nivel_socio_economico + tx_resp_q017e_A + tx_resp_q005_F * tx_resp_q004_F * tx_resp_q004_E + tx_resp_q002_A + tx_resp_q010d_B + tx_resp_q009c_A + tx_resp_q012_A + tx_resp_q010i_B +              nascidos_vivos_mae18_2019_imp + q23_D_spp,
                        data = teste %>% select(-id_escola),
                        method = "lm",
                        metric = "Rsquared",
                        trControl = trControl)


results$rf <- model_ranger$resample$Rsquared
mean(results$rf)
```
