---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(caret)
```

# Importa
```{r var selecao}
saeb <- read.csv2("../output/selecao/escolas_municipais/selecao_saeb5ef.csv")
```

```{r pilares}
pilares <- read.csv2("../output/pilares/pilar_municipais_5ef.csv")
```

# Cruza
```{r}
df <- saeb %>% 
  left_join(pilares, by = "id_escola") %>% 
  select(id_escola,
         media,
         nivel_socio_economico,
         starts_with('tx'),
         -starts_with('tx_resp_q017a'),
         starts_with('pilar')) %>% 
  mutate(nivel_socio_economico = fct_collapse(nivel_socio_economico,
                                                IV = c("Nível II","Nível III","Nível IV"),
                                                V = c("Nível V",""),
                                                VI = c("Nível VI","Nível VII")
                                                )) %>% 
  mutate_if(is.character, as.factor)

glimpse(df)
```
# CV
```{r createfolds}
set.seed(231192)
myFolds <- createFolds(df$media, k = 5)
trControl <- trainControl(
  method = "cv",
  number = 5,
  index = myFolds
)

results <- data.frame(fold = c('Fold 1', 'Fold 2', 'Fold 3', 'Fold 4', 'Fold 5'))
```


# Modelo Ranger
```{r}
set.seed(231192)
model_ranger <- train(media ~ .,
                        data = df %>% select(-id_escola),
                        method = "ranger",
                        importance = "permutation",
                        metric = "Rsquared",
                        trControl = trControl)

mean(model_ranger$resample$Rsquare)
```

```{r}
imp_ranger <- data.frame(imp = varImp(model_ranger)$importance) %>% rownames_to_column()
imp_ranger <- imp_ranger %>% 
  rename(imp = Overall) %>% 
  filter(!str_detect(rowname, "nivel")) %>%  
  arrange(desc(imp))

imp_ranger2 <- imp_ranger %>% 
  mutate(new = if_else(str_detect(rowname,'pilar'),substring(rowname,1,nchar(rowname)-1),rowname)) %>%
  distinct(new,.keep_all = TRUE)
```


"33: 0.537"
```{r}
for (i in 1:nrow(imp_ranger2)) {
  vars <- imp_ranger2[1:i,3]
  vars <- c(vars,'media', 'nivel_socio_economico')
  data <- df %>% 
    select_at(vars)
  
  myFolds <- createFolds(data$media, k = 5)
  trControl <- trainControl(
    method = "cv",
    number = 5,
    index = myFolds
  )
  
  ranger_top <- train(media ~ .,
                  data = data,
                  method = "ranger",
                  metric = "Rsquared",
                  trControl = trControl)
  r2 <- mean(ranger_top$resample$Rsquared)
  print(paste0(i, ": ",round(r2,3)))
}
```


1. nivel_socio_economico: 26,7
2. tx_resp_q012_F: 33,5
3. tx_resp_q017e_A: 40,0
4. tx_resp_q002_A: 42,1
5. pilar_familia: 46,1
6. pilar_letramento: 46,8 (melhor do que com as variáveis soltas)
7. pilar_regiao: 47,4
0. pilar_localizacao: 48,0
8. pilar_bens: 50,2
9. pilar_bens_servicos + pilar_bens_superfluos: 50,5
10. pilar_ipvs: 52,1
11. pilar_seade: 52,9
```{r}
set.seed(231192)
model_ranger_2 <- train(media ~ nivel_socio_economico + tx_resp_q012_F + tx_resp_q017e_A + tx_resp_q002_A + pilar_familia + pilar_letramento + pilar_regiao + pilar_localizacao  + pilar_bens_servicos + pilar_bens_superfluos + pilar_ipvs + pilar_seade
                        ,
                        data = df %>% select(-id_escola),
                        method = "ranger",
                        importance = "permutation",
                        metric = "Rsquared",
                        trControl = trControl)

mean(model_ranger_2$resample$Rsquare)
```



```{r}
set.seed(231192)
model_lm <- train(media ~ .,
                        data = df %>% select(-id_escola),
                        method = "lm",
                        importance = "permutation",
                        metric = "Rsquared",
                        trControl = trControl)

mean(model_lm$resample$Rsquare)
```

# Boruta ------------------------------------------------------------------
## todas variaveis confirmadas
```{r}
library(Boruta)
set.seed(231192)

train_boruta <- Boruta(media~., data = df %>% select(-id_escola), doTrace = 0)

imp_boruta <- data.frame(attStats(train_boruta))
imp_boruta <- tibble::rownames_to_column(imp_boruta, "var") %>% view()
```

```{r}
set.seed(231192)
options(warn=-1)

subsets <- c(10:37)

ctrl <- rfeControl(functions = rfFuncs,
                   method = "cv",
                   repeats = 5,
                   verbose = FALSE)


rfe_5ef <- rfe(x=df[, 2:40], 
                 y=df$media,
                 sizes = subsets,
                 rfeControl = ctrl)
```

