---
title: "Análise das escolas Saeb x Saresp"
output:
  
  html_notebook: defaultrghrteh
  pdf_document: default

---
```{r Import, include=FALSE, warning=FALSE,message=FALSE}
library(tidyverse)

# Saeb aluno
saeb3em_aluno <- read_csv("../data/microdados_saeb_2019/DADOS/TS_ALUNO_3EM.csv", na = c("*","."))
saeb9ef_aluno <- read_csv("../data/microdados_saeb_2019/DADOS/TS_ALUNO_9EF.csv", na = c("*","."))
saeb5ef_aluno <- read_csv("../data/microdados_saeb_2019/DADOS/TS_ALUNO_5EF.csv", na = c("*","."))

saeb_notas <- read_csv("../data/microdados_saeb_2019/DADOS/TS_ESCOLA.csv", na = c("*","."))
saresp_pais <- read_csv2("../data/saresp/Questionario_pais_2019.csv", na = c(NA,"NULL", "", "*"))
saresp_alunos <- read_csv2("../data/saresp/MICRODADOS_SARESP_2019.csv", na = c(NA,"NULL", "", "*"))
censo <- read_delim("../data/microdados_educacao_basica_2019/microdados_educacao_basica_2019/DADOS/ESCOLAS.CSV", delim = "|")

```

```{r filtra SP}
saeb3em_aluno <- saeb3em_aluno %>% filter(ID_UF == 35) %>% mutate(serie = '3em')
saeb9ef_aluno <- saeb9ef_aluno %>% filter(ID_UF == 35) %>% mutate(serie = '9ef')
saeb5ef_aluno <- saeb5ef_aluno %>% filter(ID_UF == 35) %>% mutate(serie = '5ef')
saeb_notas <- saeb_notas %>% filter(ID_UF == 35)
censo <- censo %>% filter(CO_UF == 35)
```

```{r colnames}
colnames(saeb3em_aluno) <- tolower(colnames(saeb3em_aluno))
colnames(saeb9ef_aluno) <- tolower(colnames(saeb9ef_aluno))
colnames(saeb5ef_aluno) <- tolower(colnames(saeb5ef_aluno))
colnames(saeb_notas) <- tolower(colnames(saeb_notas))
colnames(censo) <- tolower(colnames(censo))
colnames(saresp_alunos) <- tolower(colnames(saresp_alunos))
colnames(saresp_pais) <- tolower(colnames(saresp_pais))
```

# Saeb por escola
escolas com menos de 80% não tem notas
```{r trata saeb}

saeb_union <- saeb_notas %>% 
  filter(!is.na(nu_matriculados_censo_5ef),
         id_dependencia_adm ==2) %>% 
  transmute(
    serie = '5ef',
    id_escola,
    fl_mascara = if_else(id_escola > 60000000,1,0),
    taxa_participacao = taxa_participacao_5ef,
    media = (media_5ef_lp + media_5ef_mt)/2
  ) %>% 
  union(saeb_notas %>% 
  filter(!is.na(nu_matriculados_censo_9ef),
         id_dependencia_adm ==2) %>% 
  transmute(
    serie = '9ef',
    id_escola,
    fl_mascara = if_else(id_escola > 60000000,1,0),
    taxa_participacao = taxa_participacao_9ef,
    media = (media_9ef_lp + media_9ef_mt)/2
  )) %>% 
  union(saeb_notas %>% 
  filter(!is.na(nu_matriculados_censo_em),
         id_dependencia_adm ==2) %>% 
  transmute(
    serie = '3em',
    id_escola,
    fl_mascara = if_else(id_escola > 60000000,1,0),
    taxa_participacao = taxa_participacao_em,
    media = (media_em_lp + media_em_mt)/2
  )) %>% 
  mutate(fl_saeb = 1)

head(saeb_union)
  
```

```{r table saeb}
table(saeb_union$serie, saeb_union$fl_mascara)

prop.table(table(saeb_union$serie, saeb_union$fl_mascara),1)
```

# Saeb alunos
```{r trata saeb alunos}
trata_saeb_alunos <- function(data,serie) {
  data %>% filter(id_dependencia_adm == 2) %>% 
  group_by(id_escola) %>% 
  summarise(qtd_alunos_saeb = n(),
            perc_questionario_saeb = mean(in_preenchimento_questionario, na.rm = TRUE)) %>% 
  mutate(serie = serie)
}

saeb_alunos_union <- rbind(trata_saeb_alunos(saeb3em_aluno,'3em'),
                           trata_saeb_alunos(saeb9ef_aluno,'9ef'),
                           trata_saeb_alunos(saeb5ef_aluno,'5ef')
                           )

head(saeb_alunos_union)

```

## Cruza com saeb_alunos
```{r}
df <- saeb_union %>% 
  left_join(saeb_alunos_union, by = c("id_escola","serie"))

head(df)
```

# Saresp resultados
```{r}
trata_saresp <- function(filtro_serie, serie) {
  saresp_alunos %>% 
    filter(serie == filtro_serie,
           nomedepbol == 'Rede Estadual',
           validade == 1) %>% 
      mutate(id_escola = as.integer(paste0("35",codesc)),
             ) %>% 
        group_by(id_escola) %>% 
          summarise(qtd_alunos_saresp = n(),
                    qtd_alunos_lp_saesp = sum(particip_lp),
                    pc_alunos_lp_saresp = mean(particip_lp),
                    nota_lp_saresp = mean(profic_lp, na.rm = TRUE)
                    ) %>% 
    mutate(serie = serie,
           fl_saresp = 1,
           fl_saresp_partic = if_else(qtd_alunos_lp_saesp == 0,0,1),
           fl_saresp_partic_maior_80 = if_else(pc_alunos_lp_saresp >= 0.8,1,0))
}

saresp_union <- rbind(trata_saresp('EM-3ª série','3em'),
                           trata_saresp('9º Ano EF','9ef'),
                           trata_saresp('5º Ano EF','5ef')
                           )

head(saresp_union)
```
```{r}
df <- df %>% 
  left_join(saresp_union, by = c("id_escola", "serie"))

head(df)
```


# Saresp pais
```{r}
trata_saresp_pais <- function(filtro_serie,serie) {
  data <- saresp_pais %>% 
    filter(serie == filtro_serie) %>% 
      mutate(id_escola = as.integer(paste0("35",cd_ue))) %>% 
        group_by(id_escola) %>% 
           summarise(qtd_alunos_saresp = n(),
                     qtd_alunos_resp_saresp = sum(!is.na(q01))) %>% 
            mutate(perc_quest_saresp = round(qtd_alunos_saresp/qtd_alunos_resp_saresp,2),
                   fl_saresp_pais = 1,
                   fl_saresp_quest = if_else(qtd_alunos_resp_saresp == 0,0,1),
                   serie = serie)
}

saresp_pais_union <- rbind(trata_saresp_pais('EM-3ª série','3em'),
                           trata_saresp_pais('9º Ano EF','9ef'),
                           trata_saresp_pais('5º Ano EF','5ef')
                           )

head(saresp_pais_union)
```




```{r include=FALSE, warning=FALSE,message=FALSE}

## censo escolar 2019

censo <- censo %>% filter(CO_UF == 35) %>% 
  select(
    CO_ENTIDADE,
    NO_ENTIDADE,
    TP_DEPENDENCIA,
    TP_SITUACAO_FUNCIONAMENTO,
    CO_MUNICIPIO
  )
colnames(censo) <- tolower(colnames(censo))

data <- base_escolas %>% 
  left_join(censo, by = c("id_escola" = "co_entidade")) %>% 
  left_join(saeb_escolas, by = "id_escola") %>% 
  left_join(saresp_escolas, by = "id_escola") %>% 
  left_join(saresp_pais, by = "id_escola") %>% 
  mutate_if(is.numeric, ~replace(.,is.na(.),0)) %>% 
  left_join(saeb_notas, by = "id_escola") %>% 
  mutate(tipo = case_when(fl_saeb == 1 & fl_saresp == 1 ~ 'Saeb e Saresp',
                          fl_saeb == 1 & fl_saresp == 0 ~ 'Só Saeb',
                          fl_saeb == 0 & fl_saresp == 1 ~ 'Só Saresp',
                          ))

head(data)



```

# Escolas que estão apenas no Saeb
```{r echo=FALSE}
teste <-data %>% filter(fl_saeb == 1, fl_saresp ==0) %>% 
  select(id_escola, no_entidade)
nrow(teste)
print(teste,rownames = FALSE)
```

# Escolas que estão apenas no Saresp
```{r echo=FALSE}
teste <- data %>% filter(fl_saeb == 0, fl_saresp == 1) %>% 
  select(id_escola, no_entidade)
nrow(teste)
print(teste,rownames = FALSE)
```

# Escolas Saresp sem questionário pais
```{r echo=FALSE}
teste <- data %>% filter(fl_saresp_quest == 0, fl_saresp == 1) %>% 
  select(id_escola, no_entidade) 
nrow(teste)
print(teste,rownames = FALSE)
```

# Compara médias
```{r echo=FALSE}
teste <-data %>% 
  group_by(tipo) %>% 
  summarize(n = n(),
            media_saeb = mean(media, na.rm=TRUE))

print(teste,rownames = FALSE)
```

```{r}

```

