---
title: "Análise das variáveis Saresp Questionário - moda por escola"
subtitle: "Série `r params$serie`"
author: "Livia Kobayashi"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  pdf_document: default
params: 
  serie: '5EF'
  book: "../books/saresp5ef_pais_mode.csv"  
---

```{r include=FALSE}
knitr::opts_chunk$set(fig.align = 'center')
```

```{r echo=TRUE,message=FALSE,warning=FALSE}
library(tidyverse)
library(DataExplorer)
library(gridExtra)
library(grid)
library(caret)
library(ggcorrplot)
library(vcd)
df_publico <- read.csv2("../books/df_publico.csv")
#book <- read.csv2("../books/saresp3em_mode.csv")
book <- read.csv2(params$book)
```


```{r echo=FALSE}
#pub <- df_publico %>% filter(id_serie == '3EM')
pub <- df_publico %>% filter(id_serie == params$serie)
df <- pub %>% 
  filter(id_dependencia_adm == 'Estadual') %>% 
  filter(fl_mascara == 0) %>% 
  select(id_escola,
         nivel_socio_economico,
         nu_matriculados_censo,
         media) %>% 
  left_join(book, by = "id_escola")

select_data <- df %>% select(id_escola, media, matches("q\\d+"))
#nomes <- colnames(final_data)
#ini <- colnames(final_data)[1]
#fim <- ncol(df)
final_data <- select_data[rowSums(is.na(select_data[ , 3:ncol(select_data)])) == 0, ]
#df_filter <- df %>% filter(!is.na(mode_pais_q12),!is.na(mode_pais_q50))
#final_data <- drop_columns(df_filter, c("id_escola", "nu_matriculados_censo", "serie", "cd_ue"))

pub %>% select(id_serie) %>% head(1)
```
# Missing
```{r}
plot_missing(df)
```

# Volume
```{r,out.height = "200%", out.width="100%"}
plot_bar(final_data)
```

# Boxplot
```{r}
vars <- colnames(final_data)
vars <- vars[-c(1,2)]
plots <- list()
i <- 1
for (variable in vars) {
  #plots[[i]] <- plot_boxplot(final_data, by = variable)
  plots[[i]] <- ggplot(final_data, aes_string(variable, "media")) + geom_boxplot()
  i <- i + 1
}

n <- length(plots)

i <- 1
while (i <= n) {
  do.call("grid.arrange", c(plots[i:(min(i+5, n))], ncol=3, nrow = 2))
  i <- i + 6
}


```



# Análise Univariada
```{r}

vars <- colnames(final_data)
vars <- vars[-c(1,2)]
y_resp <- "media"

remove_cols <- nearZeroVar(df, names = TRUE)
final_cols <- setdiff(vars, remove_cols)
final_cols
tb_r2 <- data.frame(var = final_cols)

rsquared <- c()
for (variable in final_cols) {
  lm_formula <- as.formula(str_glue("{y_resp} ~ {variable}"))
  model_lm <- lm(lm_formula, df)
  rsquared <- append(rsquared, summary(model_lm)$r.squared)
}

tb_r2$rsquared <- rsquared
tb_r2 %>% head(nrow(tb_r2))

```
```{r include=FALSE}
data_corr <- df[,final_cols]

model.matrix(~0+., data=data_corr) %>% 
  cor(use="pairwise.complete.obs") %>% 
  ggcorrplot(show.diag = F, type="lower", lab=TRUE, lab_size=2, show.legend = F)
```


```{r fig.height=12, fig.width=14}

catcorrm <- function(vars, dat) sapply(vars, function(y) sapply(vars, function(x) assocstats(table(dat[,x],dat[,y]))$cramer))

matriz <- catcorrm(final_cols, data_corr)

ggcorrplot(matriz, show.diag = F, type="lower", lab=TRUE, lab_size=6, show.legend = F)
```

