---
title: "R Notebook"
output: html_notebook
params:
  serie: '5ef'
  id_serie: 5
---


```{r}
library(tidyverse)
library(caret)
library(readxl)
options(scipen = 999)
```

# Questionário Escola

## Importa
```{r ranking}

url <-  getwd()
# IEE
iee <- read.csv2(paste0(url,"/output/v2/iee_",params$serie,"_v2.csv"))
```

```{r Questionario Escola}
saeb_escola <- read.csv(paste0(url,"/data/microdados_saeb_2019_v2/DADOS/TS_ESCOLA.csv"))
colnames(saeb_escola) <- tolower(colnames(saeb_escola))
```

## Seleciona
```{r}
saeb_escola <- 
  saeb_escola %>% 
  filter(id_uf == 35,
         id_dependencia_adm == 2) %>% 
  transmute(id_escola,
            id_area = factor(id_area, labels = c("Capital", "Interior")),
             pc_formacao_docente_inicial)
```



## CRuza
```{r}
# Cruza 
data <- iee %>% 
  select(
    id_escola,
    media, 
    diff) %>% 
  left_join(
    saeb_escola, by = "id_escola"
  )

```


## R2 Univariado

### Diff
```{r}
model_lm <- lm(diff ~ pc_formacao_docente_inicial, data)
summary(model_lm)$r.squared
```
### Media
```{r}
model_lm <- lm(media ~ pc_formacao_docente_inicial, data)
summary(model_lm)$r.squared
```
O Percentual de formação docente inicial não possui relação com o IEE nem com a Média

# Questionário Diretor

## Importa
```{r Questionario Diretor}
saeb_diretor <- read_csv(paste0(url,"/data/microdados_saeb_2019_v2/DADOS/TS_DIRETOR.csv"), na = c(""))
label_diretor <- read_xlsx("data/label_questoes_saeb_2019.xlsx", sheet = "diretor")
```

## Seleciona
```{r}
colnames(saeb_diretor) <- tolower(colnames(saeb_diretor))
saeb_diretor <- 
  saeb_diretor %>% 
  filter(id_uf == 35,
         id_dependencia_adm == 2,
         in_preenchimento_questionario == 1) %>% 
  select(id_escola,
            starts_with('tx'))
```

## Cruza
```{r}
data <- iee %>% 
  select(
    id_escola,
    media, 
    diff) %>% 
  left_join(
    saeb_diretor, by = "id_escola"
  )

data %>% 
  group_by(id_escola) %>% 
  count() %>% 
  group_by(n) %>% count()

```

## Transforma
```{r}
data_t <- data %>% 
  mutate_if(is.numeric,~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)) %>% 
  mutate_if(is.character, ~replace(., is.na(.), "NA")) %>% 
  mutate_if(is.character, as.factor)
```


## NZV
```{r}
## Remove variáveis com zero ou baixa variância

remove_cols <- nearZeroVar(data_t, names = TRUE)
remove_cols 


total_vars <- colnames(data_t)
final_cols <- setdiff(total_vars, remove_cols)

data_final <- data_t[, final_cols]
paste("Nº colunas iniciais:", ncol(data_t))
paste("Nº colunas finais:", ncol(data_final))
```

## R2 Univariado

```{r}
vars_modelo <- colnames(data_final)[-c(1:3)]

# COm o efeito escola não tem relação
y_resp <- "diff"

tb_r2 <- data.frame(id_questao = vars_modelo)


rsquared <- c()

for (variable in vars_modelo) {
  lm_formula <- as.formula(str_glue("{y_resp} ~ {variable}"))
  model_lm <- lm(lm_formula, data_final)
  rsquared <- append(rsquared, summary(model_lm)$r.squared)
}
tb_r2$rsquared <- rsquared
```

```{r}
tb_r2 <- tb_r2 %>% 
  left_join(label_diretor, by = "id_questao")

tb_r2 %>%  arrange(desc(rsquared))
```



# Questionário Professor

## Importa
```{r Questionario Professor}
saeb_professor <- read_csv("data/microdados_saeb_2019_v2/DADOS/TS_PROFESSOR.csv", na = c(""))
label_professor <- read_xlsx("data/label_questoes_saeb_2019.xlsx", sheet = "professor")
```

## Seleciona
```{r}
colnames(saeb_professor) <- tolower(colnames(saeb_professor))
saeb_professor <- 
  saeb_professor %>% 
  filter(id_uf == 35,
         id_serie == params$id_serie,
         id_dependencia_adm == 2,
         in_preenchimento_questionario == 1) %>% 
  select(id_escola,
            starts_with('tx'))
```



## Cruza
```{r}
data <- iee %>% 
  select(
    id_escola,
    media, 
    diff) %>% 
  left_join(
    saeb_professor, by = "id_escola"
  )

data %>% 
  group_by(id_escola) %>% 
  count() %>% 
  group_by(n) %>% count()

```

## Transforma
```{r}
data_t <- data %>% 
  mutate_if(is.numeric,~ifelse(is.na(.x), mean(.x, na.rm = TRUE), .x)) %>% 
  mutate_if(is.character, ~replace(., is.na(.), "NA")) %>% 
  mutate_if(is.character, as.factor)
```


## NZV
```{r}
## Remove variáveis com zero ou baixa variância

remove_cols <- nearZeroVar(data_t, names = TRUE)
remove_cols 


total_vars <- colnames(data_t)
final_cols <- setdiff(total_vars, remove_cols)

data_final <- data_t[, final_cols]
paste("Nº colunas iniciais:", ncol(data_t))
paste("Nº colunas finais:", ncol(data_final))
```

## R2 Univariado

```{r}
vars_modelo <- colnames(data_final)[-c(1:3)]

# COm o efeito escola não tem relação
y_resp <- "diff"

tb_r2 <- data.frame(id_questao = vars_modelo)


rsquared <- c()

for (variable in vars_modelo) {
  lm_formula <- as.formula(str_glue("{y_resp} ~ {variable}"))
  model_lm <- lm(lm_formula, data_final)
  rsquared <- append(rsquared, summary(model_lm)$r.squared)
}
tb_r2$rsquared <- rsquared
```

```{r}
tb_r2 <- tb_r2 %>% 
  left_join(label_professor, by = "id_questao")

tb_r2 %>%  arrange(desc(rsquared))
```

