---
title: "R Notebook"
output: html_notebook
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

# Importa

## Público
```{r}
df_publico <-  read.csv2("../output/books/df_publico.csv")
```


## Saeb book prop
```{r}
saeb5ef <- read.csv2("../output/books/saeb5ef_prop.csv") %>% mutate(id_serie = '5EF')
saeb9ef <- read.csv2("../output/books/saeb9ef_prop.csv") %>% mutate(id_serie = '9EF')
saeb3em <- read.csv2("../output/books/saeb3em_prop.csv") %>% mutate(id_serie = '3EM')

saeb <- rbind(saeb5ef,saeb9ef,saeb3em)
```

## Cruza
```{r}
df <- df_publico %>% 
  filter(id_dependencia_adm == 'Estadual',
         tipo_publico != 'ETEC'
         ) %>% 
  select(id_escola,
         no_entidade,
         id_municipio,
         id_serie,
         media
         ) %>% 
  left_join(saeb, by = c("id_escola", "id_serie")) %>% 
  mutate(id_serie = factor(id_serie, levels = c('5EF','9EF','3EM')))

colnames(df)
```

# Amostra
```{r}
set.seed(231192)
amostra <-  df %>% slice_sample(weight_by = id_serie, n = 1500)
```

## Plot Variável forte
```{r}
ggplot(amostra, aes(x = tx_resp_q005_E, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Percentual de alunos cuja mãe tem ensino superior") +
  ylab("Nota média - Saeb")
```
```{r}

df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q005_E, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```
```{r}
lm(media ~ tx_resp_q005_E, df)
```


## Plot Variável média
```{r}
ggplot(amostra, aes(x = tx_resp_q009c_A, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Percentual de alunos sem computador") +
  ylab("Nota média - Saeb")
```

```{r}
df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q009c_A, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```


## Plot Variável fraca
```{r}
ggplot(amostra, aes(x = tx_resp_q001_A, y = media)) +
  geom_point(color = "black") +
  #geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Percentual de alunos cujo idioma principal é o Português") +
  ylab("Nota média - Saeb")
```

```{r}
# df  %>% 
#   group_by(id_serie) %>%
#   summarize(correlation = cor(media, tx_resp_q009a_A, method = "sp",na.rm = TRUE))

df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q001_A, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```
# Modelo


```{r}
df %>%
  filter(id_serie == '5EF') %>% 
  ggplot(aes(x = tx_resp_q002_A, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  theme_light() +
  xlab("Percentual de alunos brancos na escola") +
  ylab("Nota média - Saeb")
```
```{r}
lm(media ~ tx_resp_q002_A, df %>% filter(id_serie == '5EF'))
```

```{r}
df %>% 
  filter(id_serie == '5EF',
         tx_resp_q002_A > 0.75,
         media <= 270,
         media > 255
         )
```


# TCU

## Aspirador
```{r}
ggplot(amostra, aes(x = tx_resp_q010g_B, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Aspirador") +
  ylab("Nota média - Saeb")
```

```{r}
df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q010g_B, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```

## Percurso - carro
```{r}
ggplot(amostra, aes(x = tx_resp_q012_F, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Percurso - carro") +
  ylab("Nota média - Saeb")
```

```{r}
df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q012_F, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```

## Escrivaninha
```{r}
ggplot(amostra, aes(x = tx_resp_q010d_B, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Escrivaninha") +
  ylab("Nota média - Saeb")
```

```{r}
df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q010d_B, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```

## Não trabalha
```{r}
ggplot(amostra, aes(x = tx_resp_q017e_A, y = media)) +
  geom_point(color = "black") +
  geom_smooth(se = FALSE, color = "red4", method = "glm") + 
  facet_wrap(~id_serie) +
  theme_light() +
  xlab("Não trabalha") +
  ylab("Nota média - Saeb")
```

```{r}
df %>%
  split(.$id_serie) %>%
  map(~ lm(media ~ tx_resp_q017e_B, data=.)) %>%
  map(summary) %>%
  map_dbl("r.squared")
```